import { StrictMode, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import { assertSlot, buildQuery, rankCandidate, stages, type Candidate, type Stage, validateResumeUpload } from './domain/core';

const seed: Candidate[] = [{ id: '1', name: 'Ada Lovelace', email: 'ada@example.com', phone: '+66 81 000 0000', position: 'Tech Lead', source: 'Referral', appliedAt: '2026-08-12', stage: 'screening', version: 1, resume: 'TypeScript React Node.js 8 years clear communication' }, { id: '2', name: 'Grace Hopper', email: 'grace@example.com', phone: '+66 82 000 0000', position: 'Senior Developer', source: 'LinkedIn', appliedAt: '2026-08-10', stage: 'interview', version: 2, resume: 'JavaScript systems 10 years' }];
const jd = { id: 'jd', title: 'Tech Lead', skills: ['TypeScript', 'React'], experience: 5, culture: 'communication' };

function App() {
  const [tab, setTab] = useState('Tracker'); const [candidates, setCandidates] = useState<Candidate[]>(() => JSON.parse(localStorage.getItem('talentflow:candidates') || JSON.stringify(seed))); const [query, setQuery] = useState(''); const [resume, setResume] = useState(''); const [candidateName, setCandidateName] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [score, setScore] = useState<{ value: number; reason: string } | null>(null); const [scraperApproved, setScraperApproved] = useState(false); const [scheduled, setScheduled] = useState<Array<{ start: number; end: number }>>([]);
  const filtered = useMemo(() => candidates.filter((c) => `${c.name} ${c.email} ${c.position} ${c.source}`.toLowerCase().includes(query.toLowerCase())), [candidates, query]);
  const save = (next: Candidate[]) => { setCandidates(next); localStorage.setItem('talentflow:candidates', JSON.stringify(next)); };
  const add = () => { if (!candidateName.trim()) return setError('Candidate name is required.'); const item: Candidate = { id: crypto.randomUUID(), name: candidateName.trim(), email: `${candidateName.trim().toLowerCase().replaceAll(' ', '.')}@demo.local`, phone: '', position: 'Tech Lead', source: 'Manual', appliedAt: new Date().toISOString().slice(0, 10), stage: 'applied', version: 1 }; save([...candidates, item]); setCandidateName(''); setNotice('Candidate added to Applied.'); setError(''); };
  const edit = (candidate: Candidate) => { const name = window.prompt('Candidate name', candidate.name); if (name?.trim()) { save(candidates.map((item) => item.id === candidate.id ? { ...item, name: name.trim(), version: item.version + 1 } : item)); setNotice('Candidate updated.'); } };
  const move = (candidate: Candidate, stage: Stage) => { save(candidates.map((item) => item.id === candidate.id ? { ...item, stage, version: item.version + (stage === item.stage ? 0 : 1) } : item)); setNotice(`${candidate.name} moved to ${stage.replace('_', ' ')}.`); };
  const screen = async () => { setLoading(true); await new Promise((resolve) => setTimeout(resolve, 250)); const result = rankCandidate({ ...candidates[0], resume }, jd); setScore({ value: result.score, reason: result.reason }); setLoading(false); setNotice('Screening complete. Human review is required before rejection or offer.'); };
  const loadResume = async (file: File | undefined) => { if (!file) return; try { const bytes = new Uint8Array(await file.arrayBuffer()); validateResumeUpload({ name: file.name, type: file.type, bytes }); setResume(await file.text()); setNotice('Resume file validated by content signature.'); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'resume_type_invalid'); } };
  const approve = () => { const item = { ...seed[0], id: crypto.randomUUID(), stage: 'applied' as const, version: 1, source: 'JD search' }; save([...candidates, item]); setScraperApproved(true); setNotice(`${item.name} approved and pushed into Applicant Tracker.`); };
  const schedule = () => { try { assertSlot(scheduled, 10, 11); setScheduled([...scheduled, { start: 10, end: 11 }]); setNotice('Google Meet-compatible meeting payload created.'); } catch { setError('Conflict detected: this interviewer already has a 10:00-11:00 meeting.'); } };
  const tracker = <><section className="metrics"><div>Active candidates<strong>{candidates.length}</strong></div><div>In screening<strong>{candidates.filter((c) => c.stage === 'screening').length}</strong></div><div>Next interview<strong>Tomorrow · 10:00</strong></div></section><input className="search" placeholder="Search name, email, position, source" value={query} onChange={(e) => setQuery(e.target.value)} /><section className="board">{stages.slice(0, 5).map((stage) => <div className="lane" key={stage}><h3>{stage.replace('_', ' ')} <i>{filtered.filter((c) => c.stage === stage).length}</i></h3>{filtered.filter((c) => c.stage === stage).map((candidate) => <article key={candidate.id}><b>{candidate.name}</b><small>{candidate.position} · {candidate.source}</small><select aria-label={`Move ${candidate.name}`} value={candidate.stage} onChange={(e) => move(candidate, e.target.value as Stage)}>{stages.map((option) => <option key={option} value={option}>{option.replace('_', ' ')}</option>)}</select><button className="remove" onClick={() => edit(candidate)}>Edit</button><button className="remove" onClick={() => save(candidates.filter((item) => item.id !== candidate.id))}>Remove</button></article>)}</div>)}</section></>;
  const workspace = tab === 'Tracker' ? tracker : <section className="module"><h2>{tab}</h2>{tab === 'Scraper' && <><textarea aria-label="Job description" placeholder="Paste Job Description or criteria" /><button className="primary" onClick={() => setNotice(`Search query generated: ${buildQuery(jd)}`)}>Generate search query</button><div className="shortlist"><b>Ada Lovelace</b><span>Score 92 · Matched TypeScript, React, Node.js</span><button className="primary" onClick={approve} disabled={scraperApproved}>{scraperApproved ? 'Approved' : 'Approve & import'}</button></div><p>Demo source adapters: LinkedIn · JobsDB · Referral.</p></>}{tab === 'AI Screener' && <><textarea aria-label="Resume text" placeholder="Paste resume text or choose a PDF" value={resume} onChange={(e) => setResume(e.target.value)} /><input type="file" accept="application/pdf,text/plain" onChange={(e) => { void loadResume(e.target.files?.[0]); }} /><button className="primary" onClick={screen} disabled={loading}>{loading ? 'Screening…' : 'Run Claude-compatible screening'}</button>{score && <div className="score-card"><strong>{score.value}/100 overall match</strong><span>{score.reason}</span><b>Skills fit · 8/10</b><b>Experience fit · 8/10</b><b>Culture/communication · 7/10</b><p>Prescreen questions: explain a technical tradeoff; describe a mentoring challenge.</p></div>}</>}{tab === 'Scheduler' && <><input aria-label="Interview details" placeholder="Candidate / interviewer / time" /><button className="primary" onClick={schedule}>Create Google Meet payload</button><p>Conflict detection runs before creating a calendar event.</p></>}</section>;
  return <div className="shell"><aside><div className="logo"><b>H+</b> TalentFlow</div><small>HOTELPLUS RECRUITING OS</small>{['Overview', 'Scraper', 'AI Screener', 'Tracker', 'Scheduler'].map((item) => <button className={tab === item ? 'sel' : ''} onClick={() => setTab(item)} key={item}>{item}</button>)}<footer>Workspace / Bangkok<br /><span>Demo environment</span></footer></aside><main><header><div><small>OPERATIONS / {tab.toUpperCase()}</small><h1>{tab === 'Tracker' ? 'Applicant pipeline' : tab}</h1><p>Move every candidate forward with clear evidence and clean handoffs.</p></div><div className="add"><input aria-label="Candidate name" placeholder="Candidate name" value={candidateName} onChange={(e) => setCandidateName(e.target.value)} /><button className="primary" onClick={add}>+ Add</button></div></header>{notice && <div className="notice" role="status">{notice}</div>}{error && <div className="error" role="alert">{error}</div>}{workspace}</main></div>;
}

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
